- name: test
  hosts: localhost
  connection: local
  vars:
    jsonVrac : '[{  "hostname": "host1",  "customProperties": {    "foo": "first",    "foo2": "second"  }}, {   "hostname": "host2",   "customProperties": {     "foo": "third",     "foo2": "fourth"  }}]'
    jsonSource: |
      [
        {
            "customProperties": {
                "foo": "first",
                "foo2": "second"
            },
            "hostname": "host1"
        },
        {
            "customProperties": {
                "foo": "third",
                "foo2": "fourth"
            },
            "hostname": "host2"
        }
      ]
    yamlSource: |
      bloc1:
        key1: value1
        key2: value2
      bloc2:
        key3: value3
        key4: value4

    hostList: "{{ lookup('file', 'my.json') }}"
  tasks:

  - name: 0
    copy:
      content: "{{ yamlSource | from_yaml | to_nice_json }}"
      dest: test.json
  - name: 0
    copy:
      content: "{{ jsonSource | from_json | to_nice_yaml }}"
      dest: test.yaml
  - name: 1
    debug:
      msg: |
        {{ jsonSource | to_json }}

  
  - name: 2
    debug:
      msg: |
        {{ jsonVrac | from_json }}

