---
# tasks file for logstash


- name: Install Logstash.
  apt:
    name: logstash
    state: present

- name: Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  notify: restart logstash

- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - default.conf
  notify: restart logstash

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: yes